### PR TITLE
Upgrade to spree 2-0-stable

### PR DESCRIPTION
**Pull request by nicocharlery**

### CODE REVIEW

**Comment by bryanmtl** [comment]
@joshnuss - FYI. 

@nicocharlery :+1:

**Comment by joshnuss** [comment]
Awesomeness. Great job @nicocharley

**Comment by westonplatter** [comment]
@bryanmtl  and @joshnuss any movement on this? maybe peg out a 2-0 branch to encourage people to collocate developments? if not, i feel like make it confusing for devs doing future integrations.

**Comment by bryanmtl** [comment]
Hey @westonplatter, sorry about the delay here. I'll get those branches setup shortly.

cc: @joshnuss

**Comment by westonplatter** [comment]
@bryanmtl awesome. thanks!

**Pull request merged**
